import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const SUPABASE_URL = "https://rwxujvpakpemiwkitltk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_aN_1_fzAV3hR6FmW7FTZGg_6SF0MUHF";
const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const $ = id => document.getElementById(id);
let currentShoe=null,currentGames=[],busy=false,mode="complete",venueOptions=[];
const loginPanel=$("loginPanel"),appPanel=$("appPanel"),logoutButton=$("logoutButton"),loginMessage=$("loginMessage"),appMessage=$("appMessage");
const boolIds=["bankerPair","playerPair","bankerNatural","playerNatural","superSix"];
const DEFAULT_VENUE_KEY="baccarat_default_venue";
const LOCAL_VENUES_KEY="baccarat_local_venues";
function setSync(t,type="pending"){const e=$("syncStatus");e.textContent=t;e.className=`status ${type}`}
function showMessage(e,t,type=""){e.textContent=t;e.className=`message ${type}`.trim();clearTimeout(e._timer);if(t)e._timer=setTimeout(()=>{e.textContent="";e.className="message"},3200)}
function showSaveToast(text,type="success"){const e=$("saveToast");e.textContent=text;e.className=`save-toast ${type} show`;clearTimeout(e._timer);e._timer=setTimeout(()=>e.classList.remove("show"),1000)}
function setBusy(v){busy=v;["loginButton","addGameButton","undoButton","newShoeButton","refreshButton","modeComplete","modeWinnerOnly","confirmShoeButton","addVenueButton"].forEach(id=>{if($(id))$(id).disabled=v});document.querySelectorAll(".winner-button,.check-toggle,.count-toggle").forEach(b=>b.disabled=v)}
function winnerOf(b,p){return b>p?"莊":p>b?"閒":"和"}
function toggleBool(id,force=null){const e=$(id),next=force===null?e.getAttribute("aria-pressed")!=="true":force;e.setAttribute("aria-pressed",String(next));e.classList.toggle("selected",next);e.textContent=`${next?"☑":"☐"} ${e.textContent.replace(/^[☐☑]\s*/,"")}`}
function boolValue(id){return $(id).getAttribute("aria-pressed")==="true"}
function toggleCount(id,force=null){const e=$(id),next=force??(e.dataset.value==="2"?"3":"2");e.dataset.value=next;e.textContent=`${next} 張`;e.classList.toggle("selected",next==="3")}
function resetInputs({resetMode=false}={}){$("bankerInput").value="";$("playerInput").value="";boolIds.forEach(id=>toggleBool(id,false));toggleCount("bankerCardCount","2");toggleCount("playerCardCount","2");if(resetMode)setMode("complete")}
function nextGameNumber(){return currentGames.length?Math.max(...currentGames.map(g=>Number(g.game_number)||0))+1:1}
function setMode(next){mode=next;$("modeComplete").classList.toggle("active",next==="complete");$("modeWinnerOnly").classList.toggle("active",next==="winner_only");$("completePanel").classList.toggle("hidden",next!=="complete");$("winnerOnlyPanel").classList.toggle("hidden",next!=="winner_only");if(next==="complete")$("bankerInput").focus()}
function renderExtra(g){const items=[];if(g.record_status==="winner_only")items.push("只記勝方");if(g.banker_pair)items.push("莊對");if(g.player_pair)items.push("閒對");if(g.banker_card_count)items.push(`莊 ${g.banker_card_count} 張`);if(g.player_card_count)items.push(`閒 ${g.player_card_count} 張`);if(g.banker_natural)items.push("莊自然牌");if(g.player_natural)items.push("閒自然牌");if(g.super_six)items.push("Super 6");return items.length?`<div class="game-extra">${items.join("｜")}</div>`:""}
function render(){const next=nextGameNumber();$("shoeNumber").textContent=currentShoe?.shoe_number||"尚未建立";$("currentVenue").textContent=currentShoe?.venue||"尚未選擇";$("nextGameNumber").textContent=`第 ${next} 局`;if(document.activeElement!==$("gameNumberInput"))$("gameNumberInput").value=next;$("shoeState").textContent=currentShoe?(currentShoe.status==="open"?"進行中":"已結束"):"未開始";const can=!!currentShoe&&currentShoe.status==="open"&&!busy;$("addGameButton").disabled=!can;$("undoButton").disabled=!can||!currentGames.length;document.querySelectorAll(".winner-button").forEach(b=>b.disabled=!can);const rows=[...currentGames].sort((a,b)=>a.game_number-b.game_number).slice(-10).reverse();$("recentGames").innerHTML=rows.length?rows.map(g=>`<div class="game-row"><div class="game-main"><strong>第 ${g.game_number} 局</strong><span>${g.record_status==="winner_only"?"點數未記錄":`莊 ${g.banker_points} 點｜閒 ${g.player_points} 點`}</span><span class="winner ${g.winner==="莊"?"banker":g.winner==="閒"?"player":"tie"}">${g.winner}</span></div>${renderExtra(g)}</div>`).join(""):'<p class="empty">尚無牌局資料</p>'}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function localVenues(){try{return JSON.parse(localStorage.getItem(LOCAL_VENUES_KEY)||"[]").filter(Boolean)}catch{return[]}}
function saveLocalVenues(list){localStorage.setItem(LOCAL_VENUES_KEY,JSON.stringify([...new Set(list)]))}
async function loadVenues(){const {data,error}=await supabase.from("shoes").select("venue").not("venue","is",null);if(error)throw error;const cloud=(data||[]).map(r=>(r.venue||"").trim()).filter(Boolean);venueOptions=[...new Set([...localVenues(),...cloud])].sort((a,b)=>a.localeCompare(b,"zh-Hant"));renderVenueOptions()}
function renderVenueOptions(selected=""){const select=$("venueSelect"),preferred=selected||localStorage.getItem(DEFAULT_VENUE_KEY)||venueOptions[0]||"";select.innerHTML='<option value="">請選擇場館</option>'+venueOptions.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join("");if(venueOptions.includes(preferred))select.value=preferred}
function openShoeModal(){if(busy)return;renderVenueOptions();$("shoeNameInput").value="";$("startGameInput").value="1";$("defaultVenueCheckbox").checked=false;$("shoeModalMessage").textContent="";$("newShoeModal").classList.remove("hidden");setTimeout(()=>$("venueSelect").focus(),0)}
function closeShoeModal(){if(busy)return;$("newShoeModal").classList.add("hidden")}
function addVenue(){const raw=prompt("請輸入場館名稱");if(raw===null)return;const venue=raw.trim();if(!venue){showMessage($("shoeModalMessage"),"場館名稱不能空白","error");return}if(!venueOptions.includes(venue))venueOptions.push(venue);venueOptions.sort((a,b)=>a.localeCompare(b,"zh-Hant"));saveLocalVenues(venueOptions);renderVenueOptions(venue)}
async function loadCloudData(){setSync("同步中");const {data:shoes,error:se}=await supabase.from("shoes").select("*").eq("status","open").order("created_at",{ascending:false}).limit(1);if(se)throw se;currentShoe=shoes?.[0]||null;if(!currentShoe){currentGames=[];setSync("已連線","ok");render();return}const {data:games,error:ge}=await supabase.from("games").select("*").eq("shoe_id",currentShoe.id).order("game_number",{ascending:true});if(ge)throw ge;currentGames=games||[];setSync("已同步","ok");render()}
async function nextShoeNumber(){const {data,error}=await supabase.from("shoes").select("shoe_number");if(error)throw error;const max=(data||[]).reduce((m,r)=>Math.max(m,Number(String(r.shoe_number||"").replace(/\D/g,""))||0),0);return `S${String(max+1).padStart(6,"0")}`}
async function createNewShoe(){if(busy)return;const venue=$("venueSelect").value.trim(),name=$("shoeNameInput").value.trim(),start=Number($("startGameInput").value);if(!venue){showMessage($("shoeModalMessage"),"請先選擇或新增場館","error");return}if(!Number.isInteger(start)||start<1){showMessage($("shoeModalMessage"),"開始局數必須是 1 以上的整數","error");return}if(currentShoe?.status==="open"&&currentGames.length&&!confirm("建立新牌靴後，目前牌靴會自動結束。確定繼續嗎？"))return;setBusy(true);try{setSync("同步中");if(currentShoe?.status==="open"){const {error}=await supabase.from("shoes").update({status:"finished",finished_at:new Date().toISOString()}).eq("id",currentShoe.id);if(error)throw error}const shoe_number=await nextShoeNumber();const {data,error}=await supabase.from("shoes").insert({shoe_number,name,status:"open",venue}).select().single();if(error)throw error;currentShoe=data;currentGames=[];if($("defaultVenueCheckbox").checked)localStorage.setItem(DEFAULT_VENUE_KEY,venue);if(!venueOptions.includes(venue))venueOptions.push(venue);saveLocalVenues(venueOptions);resetInputs({resetMode:true});$("gameNumberInput").value=start;setSync("已同步","ok");showMessage(appMessage,`已開始 ${shoe_number}｜${venue}｜從第 ${start} 局記錄`,"success");$("newShoeModal").classList.add("hidden")}catch(e){console.error(e);setSync("同步失敗","error");showMessage($("shoeModalMessage"),e.message||"建立牌靴失敗","error")}finally{setBusy(false);render();$("gameNumberInput").value=start;if($("newShoeModal").classList.contains("hidden"))$("bankerInput").focus()}}
async function saveGame(winnerOnlyWinner=null){if(busy||!currentShoe||currentShoe.status!=="open")return;const gameNumber=Number($("gameNumberInput").value);if(!Number.isInteger(gameNumber)||gameNumber<1){showMessage(appMessage,"局數必須是 1 以上的整數","error");return}if(currentGames.some(g=>Number(g.game_number)===gameNumber)){showMessage(appMessage,`第 ${gameNumber} 局已存在，請改用其他局數`,"error");return}let banker=null,player=null,winner=winnerOnlyWinner,record_status="winner_only";if(!winnerOnlyWinner){banker=Number($("bankerInput").value);player=Number($("playerInput").value);if(!Number.isInteger(banker)||!Number.isInteger(player)||banker<0||banker>9||player<0||player>9){showMessage(appMessage,"莊與閒都只能輸入 0～9 的整數","error");return}winner=winnerOf(banker,player);record_status="complete"}setBusy(true);let saved=false;try{setSync("同步中");const game={shoe_id:currentShoe.id,game_number:gameNumber,banker_points:banker,player_points:player,winner,record_status,difference:record_status==="complete"?banker-player:null,banker_pair:record_status==="complete"?boolValue("bankerPair"):false,player_pair:record_status==="complete"?boolValue("playerPair"):false,banker_card_count:record_status==="complete"?Number($("bankerCardCount").dataset.value):null,player_card_count:record_status==="complete"?Number($("playerCardCount").dataset.value):null,banker_natural:record_status==="complete"?boolValue("bankerNatural"):false,player_natural:record_status==="complete"?boolValue("playerNatural"):false,super_six:record_status==="complete"?boolValue("superSix"):false};const {data,error}=await supabase.from("games").insert(game).select().single();if(error)throw error;currentGames.push(data);saved=true;resetInputs();$("gameNumberInput").value=gameNumber+1;setSync("已同步","ok");showSaveToast("✓ 已儲存到資料庫","success")}catch(e){console.error(e);setSync("同步失敗","error");showSaveToast("✕ 儲存失敗，資料已保留","error");showMessage(appMessage,e.message||"新增失敗","error")}finally{setBusy(false);render();$("gameNumberInput").value=saved?gameNumber+1:gameNumber;if(mode==="complete")$("bankerInput").focus()}}
async function deleteLastGame(){if(busy||!currentGames.length)return;const last=[...currentGames].sort((a,b)=>a.game_number-b.game_number).at(-1);if(!confirm(`確定刪除第 ${last.game_number} 局嗎？`))return;setBusy(true);try{setSync("同步中");const {error}=await supabase.from("games").delete().eq("id",last.id);if(error)throw error;currentGames=currentGames.filter(g=>g.id!==last.id);setSync("已同步","ok");showMessage(appMessage,"上一局已刪除","success")}catch(e){setSync("同步失敗","error");showMessage(appMessage,e.message||"刪除失敗","error")}finally{setBusy(false);render()}}
async function login(){if(busy)return;const email=$("emailInput").value.trim(),password=$("passwordInput").value;if(!email||!password){showMessage(loginMessage,"請輸入 Email 和密碼","error");return}setBusy(true);try{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}catch{showMessage(loginMessage,"登入失敗，請確認帳號或密碼","error")}finally{setBusy(false)}}
async function logout(){await supabase.auth.signOut()}
async function showAuthenticated(){loginPanel.classList.add("hidden");appPanel.classList.remove("hidden");logoutButton.classList.remove("hidden");try{await Promise.all([loadCloudData(),loadVenues()])}catch(e){setSync("連線失敗","error");showMessage(appMessage,e.message||"讀取雲端資料失敗","error")}}
function showLoggedOut(){loginPanel.classList.remove("hidden");appPanel.classList.add("hidden");logoutButton.classList.add("hidden");currentShoe=null;currentGames=[]}
boolIds.forEach(id=>$(id).addEventListener("click",()=>toggleBool(id)));["bankerCardCount","playerCardCount"].forEach(id=>$(id).addEventListener("click",()=>toggleCount(id)));$("modeComplete").onclick=()=>setMode("complete");$("modeWinnerOnly").onclick=()=>setMode("winner_only");$("addGameButton").onclick=()=>saveGame();document.querySelectorAll(".winner-button").forEach(b=>b.onclick=()=>saveGame(b.dataset.winner));$("newShoeButton").onclick=openShoeModal;$("confirmShoeButton").onclick=createNewShoe;$("addVenueButton").onclick=addVenue;$("closeShoeModal").onclick=closeShoeModal;$("cancelShoeButton").onclick=closeShoeModal;document.querySelector("[data-close-modal]").onclick=closeShoeModal;$("undoButton").onclick=deleteLastGame;$("refreshButton").onclick=async()=>{try{await Promise.all([loadCloudData(),loadVenues()])}catch(e){showMessage(appMessage,e.message||"重新整理失敗","error")}};$("loginButton").onclick=login;$("logoutButton").onclick=logout;$("bankerInput").addEventListener("input",()=>{if($("bankerInput").value.length===1)$("playerInput").focus()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("newShoeModal").classList.contains("hidden")){closeShoeModal();return}if(e.key!=="Enter")return;if(!loginPanel.classList.contains("hidden"))login();else if(!$("newShoeModal").classList.contains("hidden"))createNewShoe();else if(mode==="complete"&&($("bankerInput")===document.activeElement||$("playerInput")===document.activeElement))saveGame()});supabase.auth.onAuthStateChange(async(_e,s)=>s?await showAuthenticated():showLoggedOut());const {data:{session}}=await supabase.auth.getSession();if(session)await showAuthenticated();else showLoggedOut();
