import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const SUPABASE_URL = "https://rwxujvpakpemiwkitltk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_aN_1_fzAV3hR6FmW7FTZGg_6SF0MUHF";
const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
const $ = id => document.getElementById(id);
let currentShoe=null,currentGames=[],busy=false,mode="complete",venueOptions=[],allShoes=[],editingShoe=null;
const loginPanel=$("loginPanel"),appPanel=$("appPanel"),logoutButton=$("logoutButton"),loginMessage=$("loginMessage"),appMessage=$("appMessage");
const boolIds=["bankerPair","playerPair","bankerNatural","playerNatural","superSix"];
const DEFAULT_VENUE_KEY="baccarat_default_venue";
const LOCAL_VENUES_KEY="baccarat_local_venues";
function setSync(t,type="pending"){const e=$("syncStatus");e.textContent=t;e.className=`status ${type}`}
function showMessage(e,t,type=""){e.textContent=t;e.className=`message ${type}`.trim();clearTimeout(e._timer);if(t)e._timer=setTimeout(()=>{e.textContent="";e.className="message"},3200)}
function showSaveToast(text,type="success"){const e=$("saveToast");e.textContent=text;e.className=`save-toast ${type} show`;clearTimeout(e._timer);e._timer=setTimeout(()=>e.classList.remove("show"),1000)}
function setBusy(v){busy=v;["loginButton","addGameButton","undoButton","newShoeButton","refreshButton","modeComplete","modeWinnerOnly","confirmShoeButton","addVenueButton","manageShoesButton","saveEditShoeButton"].forEach(id=>{if($(id))$(id).disabled=v});document.querySelectorAll(".winner-button,.check-toggle,.count-toggle").forEach(b=>b.disabled=v)}
function winnerOf(b,p){return b>p?"莊":p>b?"閒":"和"}
function toggleBool(id,force=null){const e=$(id),next=force===null?e.getAttribute("aria-pressed")!=="true":force;e.setAttribute("aria-pressed",String(next));e.classList.toggle("selected",next);e.textContent=`${next?"☑":"☐"} ${e.textContent.replace(/^[☐☑]\s*/,"")}`}
function boolValue(id){return $(id).getAttribute("aria-pressed")==="true"}
function toggleCount(id,force=null){const e=$(id),next=force??(e.dataset.value==="2"?"3":"2");e.dataset.value=next;e.textContent=`${next} 張`;e.classList.toggle("selected",next==="3")}
function resetInputs({resetMode=false}={}){$("bankerInput").value="";$("playerInput").value="";boolIds.forEach(id=>toggleBool(id,false));toggleCount("bankerCardCount","2");toggleCount("playerCardCount","2");if(resetMode)setMode("complete")}
function nextGameNumber(){return currentGames.length?Math.max(...currentGames.map(g=>Number(g.game_number)||0))+1:1}
function setMode(next){mode=next;$("modeComplete").classList.toggle("active",next==="complete");$("modeWinnerOnly").classList.toggle("active",next==="winner_only");$("completePanel").classList.toggle("hidden",next!=="complete");$("winnerOnlyPanel").classList.toggle("hidden",next!=="winner_only");if(next==="complete")$("bankerInput").focus()}
function renderExtra(g){const items=[];if(g.record_status==="winner_only")items.push("只記勝方");if(g.banker_pair)items.push("莊對");if(g.player_pair)items.push("閒對");if(g.banker_card_count)items.push(`莊 ${g.banker_card_count} 張`);if(g.player_card_count)items.push(`閒 ${g.player_card_count} 張`);if(g.banker_natural)items.push("莊自然牌");if(g.player_natural)items.push("閒自然牌");if(g.super_six)items.push("Super 6");return items.length?`<div class="game-extra">${items.join("｜")}</div>`:""}
function render(){const next=nextGameNumber();$("shoeNumber").textContent=currentShoe?.shoe_number||"尚未建立";$("currentVenue").textContent=currentShoe?.venue||"尚未選擇";$("nextGameNumber").textContent=`第 ${next} 局`;if(document.activeElement!==$("gameNumberInput"))$("gameNumberInput").value=next;$("shoeState").textContent=currentShoe?(currentShoe.status==="open"?"進行中":"已結束"):"未開始";const can=!!currentShoe&&currentShoe.status==="open"&&!busy;$("addGameButton").disabled=!can;$("undoButton").disabled=!can||!currentGames.length;document.querySelectorAll(".winner-button").forEach(b=>b.disabled=!can);const rows=[...currentGames].sort((a,b)=>a.game_number-b.game_number).slice(-10).reverse();$("recentGames").innerHTML=rows.length?rows.map(g=>`<div class="game-row"><div class="game-main"><strong>第 ${g.game_number} 局</strong><span>${g.record_status==="winner_only"?"點數未記錄":`莊 ${g.banker_points} 點｜閒 ${g.player_points} 點`}</span><span class="winner ${g.winner==="莊"?"banker":g.winner==="閒"?"player":"tie"}">${g.winner}</span></div>${renderExtra(g)}</div>`).join(""):'<p class="empty">尚無牌局資料</p>'}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function localVenues(){try{return JSON.parse(localStorage.getItem(LOCAL_VENUES_KEY)||"[]").filter(Boolean)}catch{return[]}}
function saveLocalVenues(list){localStorage.setItem(LOCAL_VENUES_KEY,JSON.stringify([...new Set(list)]))}
async function loadVenues(){const {data,error}=await supabase.from("shoes").select("venue").not("venue","is",null);if(error)throw error;const cloud=(data||[]).map(r=>(r.venue||"").trim()).filter(Boolean);venueOptions=[...new Set([...localVenues(),...cloud])].sort((a,b)=>a.localeCompare(b,"zh-Hant"));renderVenueOptions()}
function renderVenueOptions(selected=""){const select=$("venueSelect"),preferred=selected||localStorage.getItem(DEFAULT_VENUE_KEY)||venueOptions[0]||"";select.innerHTML='<option value="">請選擇場館</option>'+venueOptions.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join("");if(venueOptions.includes(preferred))select.value=preferred}
function openShoeModal(){if(busy)return;renderVenueOptions();$("shoeNameInput").value="";$("startGameInput").value="1";$("defaultVenueCheckbox").checked=false;$("shoeModalMessage").textContent="";$("newShoeModal").classList.remove("hidden");setTimeout(()=>$("venueSelect").focus(),0)}
function closeShoeModal(){if(busy)return;$("newShoeModal").classList.add("hidden")}
function addVenue(){const raw=prompt("請輸入場館名稱");if(raw===null)return;const venue=raw.trim();if(!venue){showMessage($("shoeModalMessage"),"場館名稱不能空白","error");return}if(!venueOptions.includes(venue))venueOptions.push(venue);venueOptions.sort((a,b)=>a.localeCompare(b,"zh-Hant"));saveLocalVenues(venueOptions);renderVenueOptions(venue)}
async function loadCloudData(){setSync("同步中");const {data:shoes,error:se}=await supabase.from("shoes").select("*").eq("status","open").eq("is_archived",false).order("created_at",{ascending:false}).limit(1);if(se)throw se;currentShoe=shoes?.[0]||null;if(!currentShoe){currentGames=[];setSync("已連線","ok");render();return}const {data:games,error:ge}=await supabase.from("games").select("*").eq("shoe_id",currentShoe.id).order("game_number",{ascending:true});if(ge)throw ge;currentGames=games||[];setSync("已同步","ok");render()}
async function nextShoeNumber(){const {data,error}=await supabase.from("shoes").select("shoe_number");if(error)throw error;const max=(data||[]).reduce((m,r)=>Math.max(m,Number(String(r.shoe_number||"").replace(/\D/g,""))||0),0);return `S${String(max+1).padStart(6,"0")}`}
async function createNewShoe(){if(busy)return;const venue=$("venueSelect").value.trim(),name=$("shoeNameInput").value.trim(),start=Number($("startGameInput").value);if(!venue){showMessage($("shoeModalMessage"),"請先選擇或新增場館","error");return}if(!Number.isInteger(start)||start<1){showMessage($("shoeModalMessage"),"開始局數必須是 1 以上的整數","error");return}if(currentShoe?.status==="open"&&currentGames.length&&!confirm("建立新牌靴後，目前牌靴會自動結束。確定繼續嗎？"))return;setBusy(true);try{setSync("同步中");if(currentShoe?.status==="open"){const {error}=await supabase.from("shoes").update({status:"finished",finished_at:new Date().toISOString()}).eq("id",currentShoe.id);if(error)throw error}const shoe_number=await nextShoeNumber();const {data,error}=await supabase.from("shoes").insert({shoe_number,name,status:"open",venue}).select().single();if(error)throw error;currentShoe=data;currentGames=[];if($("defaultVenueCheckbox").checked)localStorage.setItem(DEFAULT_VENUE_KEY,venue);if(!venueOptions.includes(venue))venueOptions.push(venue);saveLocalVenues(venueOptions);resetInputs({resetMode:true});$("gameNumberInput").value=start;setSync("已同步","ok");showMessage(appMessage,`已開始 ${shoe_number}｜${venue}｜從第 ${start} 局記錄`,"success");$("newShoeModal").classList.add("hidden")}catch(e){console.error(e);setSync("同步失敗","error");showMessage($("shoeModalMessage"),e.message||"建立牌靴失敗","error")}finally{setBusy(false);render();$("gameNumberInput").value=start;if($("newShoeModal").classList.contains("hidden"))$("bankerInput").focus()}}
async function saveGame(winnerOnlyWinner=null){if(busy||!currentShoe||currentShoe.status!=="open")return;const gameNumber=Number($("gameNumberInput").value);if(!Number.isInteger(gameNumber)||gameNumber<1){showMessage(appMessage,"局數必須是 1 以上的整數","error");return}if(currentGames.some(g=>Number(g.game_number)===gameNumber)){showMessage(appMessage,`第 ${gameNumber} 局已存在，請改用其他局數`,"error");return}let banker=null,player=null,winner=winnerOnlyWinner,record_status="winner_only";if(!winnerOnlyWinner){banker=Number($("bankerInput").value);player=Number($("playerInput").value);if(!Number.isInteger(banker)||!Number.isInteger(player)||banker<0||banker>9||player<0||player>9){showMessage(appMessage,"莊與閒都只能輸入 0～9 的整數","error");return}winner=winnerOf(banker,player);record_status="complete"}setBusy(true);let saved=false;try{setSync("同步中");const game={shoe_id:currentShoe.id,game_number:gameNumber,banker_points:banker,player_points:player,winner,record_status,difference:record_status==="complete"?banker-player:null,banker_pair:record_status==="complete"?boolValue("bankerPair"):false,player_pair:record_status==="complete"?boolValue("playerPair"):false,banker_card_count:record_status==="complete"?Number($("bankerCardCount").dataset.value):null,player_card_count:record_status==="complete"?Number($("playerCardCount").dataset.value):null,banker_natural:record_status==="complete"?boolValue("bankerNatural"):false,player_natural:record_status==="complete"?boolValue("playerNatural"):false,super_six:record_status==="complete"?boolValue("superSix"):false};const {data,error}=await supabase.from("games").insert(game).select().single();if(error)throw error;currentGames.push(data);saved=true;resetInputs();$("gameNumberInput").value=gameNumber+1;setSync("已同步","ok");showSaveToast("✓ 已儲存到資料庫","success")}catch(e){console.error(e);setSync("同步失敗","error");showSaveToast("✕ 儲存失敗，資料已保留","error");showMessage(appMessage,e.message||"新增失敗","error")}finally{setBusy(false);render();$("gameNumberInput").value=saved?gameNumber+1:gameNumber;if(mode==="complete")$("bankerInput").focus()}}

function formatDate(value){if(!value)return "—";try{return new Intl.DateTimeFormat("zh-TW",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}catch{return "—"}}
function closeManagerModal(){if(busy)return;$(`shoeManagerModal`).classList.add("hidden")}
function closeDetailModal(){$("shoeDetailModal").classList.add("hidden")}
function closeEditModal(){if(busy)return;$(`editShoeModal`).classList.add("hidden");editingShoe=null}
async function openShoeManager(){if(busy)return;$(`shoeManagerModal`).classList.remove("hidden");$("managerMessage").textContent="";await loadShoeManager()}
async function loadShoeManager(){try{$("shoeManagerList").innerHTML='<p class="empty">讀取中…</p>';const {data,error}=await supabase.from("shoes").select("*").order("created_at",{ascending:false});if(error)throw error;const {data:gameRows,error:gameError}=await supabase.from("games").select("shoe_id");if(gameError)throw gameError;const counts=(gameRows||[]).reduce((m,g)=>(m[g.shoe_id]=(m[g.shoe_id]||0)+1,m),{});allShoes=(data||[]).map(shoe=>({...shoe,game_count:counts[shoe.id]||0}));renderShoeManager()}catch(e){console.error(e);showMessage($("managerMessage"),e.message||"讀取牌靴失敗","error")}}
function filteredShoes(){const q=$("shoeSearchInput").value.trim().toLowerCase(),status=$("shoeStatusFilter").value;return allShoes.filter(s=>{const archived=!!s.is_archived;if(status==="active"&&archived)return false;if(status==="archived"&&!archived)return false;const text=[s.shoe_number,s.name,s.venue].filter(Boolean).join(" ").toLowerCase();return !q||text.includes(q)})}
function renderShoeManager(){const list=filteredShoes();$("shoeManagerList").innerHTML=list.length?list.map(s=>{const active=currentShoe?.id===s.id,archived=!!s.is_archived;return `<div class="shoe-manager-row ${archived?"archived-row":""}"><div class="shoe-manager-main"><strong>${escapeHtml(s.shoe_number||"未命名")}${active?'<span class="active-shoe-marker">目前</span>':""}</strong><small>${escapeHtml(s.name||"未填名稱")}</small></div><div><strong>${escapeHtml(s.venue||"未選場館")}</strong><div class="shoe-manager-meta">${archived?"已封存":s.status==="open"?"進行中":"已結束"}</div></div><div class="shoe-manager-meta">${Number(s.game_count)||"—"}</div><div class="shoe-manager-meta">${formatDate(s.created_at)}</div><div class="shoe-actions"><button class="secondary" data-action="view" data-id="${s.id}">查看</button><button class="warning" data-action="edit" data-id="${s.id}">修改</button><button class="${archived?"restore":"archive"}" data-action="archive" data-id="${s.id}">${archived?"復原":"封存"}</button><button class="danger" data-action="delete" data-id="${s.id}">刪除</button></div></div>`}).join(""):'<p class="empty">沒有符合條件的牌靴</p>';document.querySelectorAll("#shoeManagerList [data-action]").forEach(b=>b.onclick=()=>handleShoeAction(b.dataset.action,b.dataset.id))}
async function handleShoeAction(action,id){const shoe=allShoes.find(s=>String(s.id)===String(id));if(!shoe)return;if(action==="view")return viewShoe(shoe);if(action==="edit")return openEditShoe(shoe);if(action==="archive")return toggleArchiveShoe(shoe);if(action==="delete")return deleteShoe(shoe)}
async function viewShoe(shoe){$("shoeDetailTitle").textContent=`${shoe.shoe_number} 牌靴內容`;$("shoeDetailMeta").textContent=`${shoe.venue||"未選場館"}｜${shoe.name||"未填名稱"}`;$("shoeDetailGames").innerHTML='<p class="empty">讀取中…</p>';$("shoeDetailModal").classList.remove("hidden");try{const {data,error}=await supabase.from("games").select("*").eq("shoe_id",shoe.id).order("game_number",{ascending:true});if(error)throw error;const games=data||[];$("shoeDetailMeta").textContent=`${shoe.venue||"未選場館"}｜共 ${games.length} 局｜${formatDate(shoe.created_at)}`;$("shoeDetailGames").innerHTML=games.length?games.map(g=>`<div class="detail-game-row"><strong>第 ${g.game_number} 局｜${g.winner}</strong><div class="shoe-manager-meta">${g.record_status==="winner_only"?"只記勝方":`莊 ${g.banker_points} 點｜閒 ${g.player_points} 點`}</div>${renderExtra(g)}</div>`).join(""):'<p class="empty">這個牌靴尚無牌局</p>'}catch(e){$("shoeDetailGames").innerHTML=`<p class="empty">${escapeHtml(e.message||"讀取失敗")}</p>`}}
function openEditShoe(shoe){editingShoe=shoe;const select=$("editVenueSelect");const options=[...new Set([...venueOptions,shoe.venue].filter(Boolean))].sort((a,b)=>a.localeCompare(b,"zh-Hant"));select.innerHTML='<option value="">請選擇場館</option>'+options.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join("");select.value=shoe.venue||"";$("editShoeNameInput").value=shoe.name||"";$("editShoeMessage").textContent="";$("editShoeModal").classList.remove("hidden")}
async function saveEditedShoe(){if(busy||!editingShoe)return;const venue=$("editVenueSelect").value.trim(),name=$("editShoeNameInput").value.trim();if(!venue){showMessage($("editShoeMessage"),"請選擇場館","error");return}setBusy(true);try{const {data,error}=await supabase.from("shoes").update({venue,name}).eq("id",editingShoe.id).select().single();if(error)throw error;allShoes=allShoes.map(s=>s.id===data.id?{...data,game_count:s.game_count||0}:s);if(currentShoe?.id===data.id)currentShoe=data;if(!venueOptions.includes(venue)){venueOptions.push(venue);saveLocalVenues(venueOptions)}render();renderShoeManager();showSaveToast("✓ 牌靴資料已更新","success");$("editShoeModal").classList.add("hidden");editingShoe=null}catch(e){showMessage($("editShoeMessage"),e.message||"修改失敗","error")}finally{setBusy(false)}}
async function toggleArchiveShoe(shoe){const willArchive=!shoe.is_archived;if(willArchive&&currentShoe?.id===shoe.id&&!confirm(`這是目前進行中的 ${shoe.shoe_number}。封存後將無法繼續記錄，確定封存嗎？`))return;if(!willArchive&&!confirm(`確定復原 ${shoe.shoe_number} 嗎？`))return;setBusy(true);try{const updates={is_archived:willArchive,archived_at:willArchive?new Date().toISOString():null};if(willArchive&&shoe.status==="open")updates.status="finished",updates.finished_at=new Date().toISOString();const {data,error}=await supabase.from("shoes").update(updates).eq("id",shoe.id).select().single();if(error)throw error;allShoes=allShoes.map(s=>s.id===data.id?{...data,game_count:s.game_count||0}:s);if(currentShoe?.id===shoe.id&&willArchive){currentShoe=null;currentGames=[]}render();renderShoeManager();showSaveToast(willArchive?"✓ 牌靴已封存":"✓ 牌靴已復原","success")}catch(e){showMessage($("managerMessage"),e.message||"操作失敗","error")}finally{setBusy(false)}}
async function deleteShoe(shoe){const {count,error:ce}=await supabase.from("games").select("id",{count:"exact",head:true}).eq("shoe_id",shoe.id);if(ce){showMessage($("managerMessage"),ce.message||"無法確認牌局數","error");return}const warning=`確定永久刪除 ${shoe.shoe_number}？\n場館：${shoe.venue||"未選場館"}\n共 ${count||0} 局\n\n此操作無法復原。`;if(!confirm(warning))return;setBusy(true);try{let r=await supabase.from("games").delete().eq("shoe_id",shoe.id);if(r.error)throw r.error;r=await supabase.from("shoes").delete().eq("id",shoe.id);if(r.error)throw r.error;allShoes=allShoes.filter(s=>s.id!==shoe.id);if(currentShoe?.id===shoe.id){currentShoe=null;currentGames=[]}render();renderShoeManager();showSaveToast("✓ 牌靴已永久刪除","success")}catch(e){showMessage($("managerMessage"),e.message||"刪除失敗","error")}finally{setBusy(false)}}

async function deleteLastGame(){if(busy||!currentGames.length)return;const last=[...currentGames].sort((a,b)=>a.game_number-b.game_number).at(-1);if(!confirm(`確定刪除第 ${last.game_number} 局嗎？`))return;setBusy(true);try{setSync("同步中");const {error}=await supabase.from("games").delete().eq("id",last.id);if(error)throw error;currentGames=currentGames.filter(g=>g.id!==last.id);setSync("已同步","ok");showMessage(appMessage,"上一局已刪除","success")}catch(e){setSync("同步失敗","error");showMessage(appMessage,e.message||"刪除失敗","error")}finally{setBusy(false);render()}}
async function login(){if(busy)return;const email=$("emailInput").value.trim(),password=$("passwordInput").value;if(!email||!password){showMessage(loginMessage,"請輸入 Email 和密碼","error");return}setBusy(true);try{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}catch{showMessage(loginMessage,"登入失敗，請確認帳號或密碼","error")}finally{setBusy(false)}}
async function logout(){await supabase.auth.signOut()}
async function showAuthenticated(){loginPanel.classList.add("hidden");appPanel.classList.remove("hidden");logoutButton.classList.remove("hidden");try{await Promise.all([loadCloudData(),loadVenues()])}catch(e){setSync("連線失敗","error");showMessage(appMessage,e.message||"讀取雲端資料失敗","error")}}
function showLoggedOut(){loginPanel.classList.remove("hidden");appPanel.classList.add("hidden");logoutButton.classList.add("hidden");currentShoe=null;currentGames=[]}
boolIds.forEach(id=>$(id).addEventListener("click",()=>toggleBool(id)));["bankerCardCount","playerCardCount"].forEach(id=>$(id).addEventListener("click",()=>toggleCount(id)));$("modeComplete").onclick=()=>setMode("complete");$("modeWinnerOnly").onclick=()=>setMode("winner_only");$("addGameButton").onclick=()=>saveGame();document.querySelectorAll(".winner-button").forEach(b=>b.onclick=()=>saveGame(b.dataset.winner));$("newShoeButton").onclick=openShoeModal;$("confirmShoeButton").onclick=createNewShoe;$("addVenueButton").onclick=addVenue;$("closeShoeModal").onclick=closeShoeModal;$("cancelShoeButton").onclick=closeShoeModal;document.querySelector("[data-close-modal]").onclick=closeShoeModal;$("manageShoesButton").onclick=openShoeManager;$("closeManagerModal").onclick=closeManagerModal;document.querySelector("[data-close-manager]").onclick=closeManagerModal;$("shoeSearchInput").oninput=renderShoeManager;$("shoeStatusFilter").onchange=renderShoeManager;$("closeDetailModal").onclick=closeDetailModal;document.querySelector("[data-close-detail]").onclick=closeDetailModal;$("closeEditModal").onclick=closeEditModal;$("cancelEditShoeButton").onclick=closeEditModal;document.querySelector("[data-close-edit]").onclick=closeEditModal;$("saveEditShoeButton").onclick=saveEditedShoe;$("undoButton").onclick=deleteLastGame;$("refreshButton").onclick=async()=>{try{await Promise.all([loadCloudData(),loadVenues()])}catch(e){showMessage(appMessage,e.message||"重新整理失敗","error")}};$("loginButton").onclick=login;$("logoutButton").onclick=logout;$("bankerInput").addEventListener("input",()=>{if($("bankerInput").value.length===1)$("playerInput").focus()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(!$("editShoeModal").classList.contains("hidden")){closeEditModal();return}if(!$("shoeDetailModal").classList.contains("hidden")){closeDetailModal();return}if(!$("shoeManagerModal").classList.contains("hidden")){closeManagerModal();return}if(!$("newShoeModal").classList.contains("hidden")){closeShoeModal();return}}if(e.key!=="Enter")return;if(!loginPanel.classList.contains("hidden"))login();else if(!$("newShoeModal").classList.contains("hidden"))createNewShoe();else if(mode==="complete"&&($("bankerInput")===document.activeElement||$("playerInput")===document.activeElement))saveGame()});supabase.auth.onAuthStateChange(async(_e,s)=>s?await showAuthenticated():showLoggedOut());const {data:{session}}=await supabase.auth.getSession();if(session)await showAuthenticated();else showLoggedOut();
